name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    

    - run: echo "CONTAINER_NAME=wkstagg-test:$(date +%s)" >> $GITHUB_ENV
      name: Set container name
    
    - run: echo $(CONTAINER_NAME); docker build . --file Dockerfile --tag $CONTAINER_NAME
      name: Build the Docker image
            
      # You may pin to the exact commit or the version.
      # uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
    - uses: aquasecurity/trivy-action@0.29.0
      name: Aqua Security Trivy
      with:
        image-ref: ${{ env.CONTAINER_NAME }}
        ignore-unfixed: true
        hide-progress: true
        format: 'json'
        output: 'trivy-scan-1.json'
        
    - uses: project-copacetic/copa-action@v1.1.0
      name: Copacetic Action
      with:
        # The image reference to patch
        image: ${{ env.CONTAINER_NAME }}
        # The trivy json report of the image to patch
        image-report: 'trivy-scan-1.json'
        # The new patched image tag
        patched-tag: '-patched'

    - uses: aquasecurity/trivy-action@0.29.0
      name: Aqua Security Trivy (post patch)
      with:
        image-ref: "${{ env.CONTAINER_NAME }}-patched"
        ignore-unfixed: true
        hide-progress: true
        format: 'json'
        output: 'trivy-scan-1.json'
          
    
